language: node_js

node_js:
  - '7'

cache:
  directories:
    - node_modules

before_script:
  - npm install -g typescript mocha tslint

script:
  - npm run lint
  - npm run build
  - npm run ci:test:unit

deploy:
  provider: npm
  email: contact@ohira-nao.net
  api_key:
    secure: GbP1krgutlH8V3JjL7z+U9wwNalf6/Dj/zxOJ8DJ8UW7C8YE3fa02rCx3XACWYo0INmdgzzvCIOl1sAycAHZmvLeuNJYRIhGk4fbj85VaYgn+jZaQOtzGcu0RRaZaT6ixD7htnpkYdxDU6Kby4MdqtjJmPzKDQ3GsVtXMNfMk5UjIPQlUlP2AYNzR6QlPwLR5U4ThZZ5O+NQoVAnAl/LHzb/cNwF24ChsPH0+LyJZ0rcsNAxyCVErqkJm25XToLr/QCEA53W87s/dx06j5ubjl7zIHAm92Ia2EKAlbabKU8CYIVQI4gHTHn6ahbOfdhWI91lbRTNd6YpjMAL7hmSkSpPy6BVe8uDIc+MZw//zs8YDC4kauOF/p+KOKDI0FwtvzPDz0Auu1QN7oEuiWVh/I0qOZpt4FHLzUt9aKTFns7eOQEq8FXZHz1d+/4z+4TXoslTGxGyUKC35wLQNud7LN/zIwgb2wNu1/fB6WrBFOsYwfbXa+RYHOPlUG3JeK+VhM5aIfsWTnbUMZFJrtT4VY5qhbI0mU/+BqKjRkmJOHs6smv391wk4gSviwQKdsIBGxy99IsIPNO2e1XOHICPxgKLASuZpqn/PutxOV2serbdJznA5EUVBR1qQLHQt0CSLspTYYARBAK5szFx5MKgJxzC4qmOsN5sehy3NulAg/4=
  on:
    - tags: true
