language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules # NPM packages
before_script:
  - npm install -g typescript mocha tslint npm-run-all rimraf np
script:
  - npm run lint
  - npm run build
  - npm run ci:test:unit